name: Deploy My Website

on:
  push:
    branches:
      - main # Change if you want another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 4️⃣ Setup Node.js
      - name: Setup Node Modules
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # 5️⃣ Install frontend dependencies
      - name: Install NPM dependencies
        run: npm ci

      # 6️⃣ Build Inertia / React assets
      - name: Build frontend assets
        run: npm run build

      - name: Deploy to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.omolayoayokanmi.name.ng
          username: ${{ secrets.FTP_USERNAME_O }}
          password: ${{ secrets.FTP_PASSWORD_O }}
          local-dir: ./ # root of repo
          server-dir: ./ # root folder on server
          delete: false
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/tests/**
            .env
            public/storage/**
